name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u dhammikamahendra --password-stdin

      - name: Build the Docker image
        run: docker build -t ghcr.io/dhammikamahendra/lexolootback:v1 .

      - name: Push the Docker image
        run: docker push ghcr.io/dhammikamahendra/lexolootback:v1
