# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Nodeback

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d86d38413eb841a488bf3ade32877de0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_93588cfb92704c3e9dfee30a3f99f728 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_d86d38413eb841a488bf3ade32877de0 }}/dhammikamahendra/lexolootback:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Nodeback'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d77582dd6294445b9983cc4ff3714196 }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_d86d38413eb841a488bf3ade32877de0 }}/dhammikamahendra/lexolootback:${{ github.sha }}'